application: asheville-io
version: 1
threadsafe: true
api_version: 1
default_expiration: 1d

runtime: python27

libraries:
- name: ssl
  version: latest

handlers:

# static
- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.*\.html)
  static_files: \1
  upload: (.*)\.html
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /main.css
  static_files: main.css
  upload: main.css

# dynamic
- url: /dropbox/.*
  script: dropbox.application
  secure: always

- url: /facebook/.*
  script: facebook.application
  secure: always

- url: /instagram/.*
  script: instagram.application
  secure: always

- url: /googleplus/.*
  script: googleplus.application
  secure: always
  login: required

- url: /twitter/.*
  script: twitter.application
  secure: always

- url: /(migrate|migration/.*)
  script: migrations.application
  secure: always

- url: /_ah/queue/.*
  script: tasks.application
  login: admin

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
# don't need anything in the submodule subdirs, especially since
# webapp-improved/lib has over 1k files!
- ^(.*/)?gdata-python-client/(pydocs|samples|tests)/.*
- ^(.*/)?google-api-python-client/(docs|samples|tests)/.*
- ^(.*/)?httplib2_module/(doc|python3|ref|test).*
- ^(.*/)?webutil/webapp-improved/.*/.*
- ^(.*/)?oauthlib_module/(docs|tests)/.*
- ^(.*/)?python-gflags/(debian|tests)/.*
- ^(.*/)?requests_module/docs/.*
- ^(.*/)?requests_oauthlib_module/tests/.*

